language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

sudo: false

before_script:
  - composer install
  - cd vendor/bin && ls -lah

script:
  - bash ./vendor/bin/phpunit