language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 5.2
    - php: 5.3

sudo: false

before_script:
  - composer require phpunit/phpunit
  - npm install -g gulp-cli
  - npm install

script:
  - ./vendor/bin/phpunit

dist: trusty